### ISSUE TITLE
Support the input file format to YAML

### ISSUE THREAD

**Issue by rabin-io** [Julien-cpsn/ATAC#30]
Just a suggestion, can you add support for yaml as the input for the collection, yaml is more _human_ friendly, for read and write. You can also have references ([anchors](https://support.atlassian.com/bitbucket-cloud/docs/yaml-anchors/)) to reduce repetitive blocks.

Just a thought :)

**Comment by Julien-cpsn** [comment]
Hello!

I personnally really do not like (hate) Yaml files. In contexts where you can have tabulated or big text it's by far one of the most unpractical things (e.g. request body).

I am not closed to the idea though

Have a great day

**Comment by rabin-io** [comment]
YAML and JSON are pretty much interchangeable, but YAML do have some benefits over JSON when it comes to human-readable (and editing).

Take the file [auth.json](https://github.com/Julien-cpsn/ATAC/blob/main/base_collections/auth.json) for example, it can be written almost half of the length. Which I find much easier to skim with the eyes, without all the extra fluff of JSON with quotes and curly braces.

```yaml
---
name: Auth
requests:
- name: Test Basic Auth
  url: https://httpbin.org/basic-auth/username/pwd
  method: GET
  params: []
  headers: &default_headers
  - enabled: true
    data:
    - cache-control
    - no-cache
  - enabled: true
    data:
    - user-agent
    - ATAC/v0.7.0
  - enabled: true
    data:
    - accept
    - "*/*"
  - enabled: true
    data:
    - accept-encoding
    - gzip, deflate, br
  - enabled: true
    data:
    - connection
    - keep-alive
  body: no_body
  auth:
    basic_auth:
    - username
    - password
  settings: &default_settings
    use_config_proxy: true
    allow_redirects: true
    store_received_cookies: true
    pretty_print_response_content: true
- name: Test Bearer Auth
  url: https://httpbin.org/bearer
  method: GET
  params: []
  headers:
  <<: *default_headers
  body: no_body
  auth:
    bearer_token: my_bearer=
  settings:
    <<: *default_settings
```
